apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2021-11-08T14:40:39Z"
  name: releaser-sample-v0.0.9
  namespace: default
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
      provider: github
    secret: {}
  phase: draft
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: master
    name: test
    provider: github
    version: v0.0.9
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.5
status: {}
