apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  labels:
    app.kubernetes.io/instance: bot
  name: releaser-sample-v0.0.20
  namespace: default
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
    secret: {}
  phase: ready
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: main
    name: test
    provider: github
    version: v0.0.20
  - action: release
    address: https://github.com/linuxsuren-bot/jenkins-cli
    branch: master
    name: jenkins-cli
    provider: github
    version: v0.0.34
  secret:
    name: github
    namespace: linuxsuren-bot
  version: v0.0.20
status:
  conditions:
  - conditionType: release
    message: https://github.com/linuxsuren-bot/test was released
    status: success
