apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: "2021-11-07T13:29:01Z"
  labels:
    app.kubernetes.io/instance: bot
  name: releaser-sample-v0.0.25
  namespace: default
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
      provider: github
    secret: {}
  phase: ready
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: main
    name: test
    provider: github
    version: v0.0.25
  - action: auto
    address: https://github.com/linuxsuren-bot/jenkins-cli
    branch: master
    name: jenkins-cli
    provider: github
    version: v0.0.37-alpha.3
  secret:
    name: github
    namespace: linuxsuren-bot
  version: v0.0.25
status: {}
