apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"name":"releaser-sample-v0.0.10","namespace":"argocd"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/linuxsuren-bot/linuxsuren-releaser","branch":"master","name":"test"}},"repositories":[{"action":"release","address":"https://github.com/linuxsuren-bot/test","branch":"master","name":"test","provider":"github","version":"v0.0.8"}],"secret":{"name":"test-git","namespace":"default"},"version":"v0.0.4"}}
    releaser.devops.kubesphere.io/hash: 6cc4499dfc
  creationTimestamp: "2021-11-25T10:41:06Z"
  generation: 2
  name: releaser-sample-v0.0.10
  namespace: argocd
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/argocd/releasers/releaser-sample-v0.0.10
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: master
    name: test
    provider: github
    version: v0.0.8
  secret:
    name: test-git
    namespace: default
  version: v0.0.4
status:
  conditions:
  - conditionType: release
    message: https://github.com/linuxsuren-bot/test was released
    status: success
