apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{"releaser.devops.kubesphere.io/hash":"5cd4674fcc"},"creationTimestamp":"2021-11-06T15:32:14Z","generation":2,"labels":{"app.kubernetes.io/instance":"bot"},"name":"releaser-sample-v0.0.23","namespace":"default","selfLink":"/apis/devops.kubesphere.io/v1alpha1/namespaces/default/releasers/releaser-sample-v0.0.22"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/linuxsuren-bot/linuxsuren-releaser","branch":"master","name":"test"},"secret":{}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/linuxsuren-bot/test","branch":"main","name":"test","provider":"github","version":"v0.0.23"},{"action":"release","address":"https://github.com/linuxsuren-bot/jenkins-cli","branch":"master","name":"jenkins-cli","provider":"github","version":"v0.0.37-alpha.1"}],"secret":{"name":"github","namespace":"linuxsuren-bot"},"version":"v0.0.23"},"status":{"conditions":[{"conditionType":"release","message":"https://github.com/linuxsuren-bot/test was released","status":"success"},{"conditionType":"release","message":"https://github.com/linuxsuren-bot/jenkins-cli was released","status":"success"}]}}
    releaser.devops.kubesphere.io/hash: 5cd4674fcc
  creationTimestamp: "2021-11-06T15:42:28Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: bot
  name: releaser-sample-v0.0.23
  namespace: default
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/default/releasers/releaser-sample-v0.0.23
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: main
    name: test
    provider: github
    version: v0.0.23
  - action: release
    address: https://github.com/linuxsuren-bot/jenkins-cli
    branch: master
    name: jenkins-cli
    provider: github
    version: v0.0.37-alpha.1
  secret:
    name: github
    namespace: linuxsuren-bot
  version: v0.0.23
status:
  conditions:
  - conditionType: release
    message: https://github.com/linuxsuren-bot/test was released
    status: success
  - conditionType: release
    message: https://github.com/linuxsuren-bot/jenkins-cli was released
    status: success
