apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"devops.kubesphere.io/v1alpha1","kind":"Releaser","metadata":{"annotations":{},"name":"releaser-sample-v0.0.9","namespace":"default"},"spec":{"gitOps":{"enable":true,"repository":{"address":"https://github.com/linuxsuren-bot/linuxsuren-releaser","branch":"master","name":"test"}},"phase":"ready","repositories":[{"action":"release","address":"https://github.com/linuxsuren-bot/test","branch":"master","name":"test","provider":"github","version":"v0.0.8"}],"secret":{"name":"linuxsuren-bot","namespace":"ks-releaser-system"},"version":"v0.0.4"}}
    releaser.devops.kubesphere.io/hash: cfc9598c6
  creationTimestamp: "2021-11-08T14:40:39Z"
  generation: 1
  name: releaser-sample-v0.0.9
  namespace: default
  selfLink: /apis/devops.kubesphere.io/v1alpha1/namespaces/default/releasers/releaser-sample-v0.0.9
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/linuxsuren-releaser
      branch: master
      name: test
      provider: github
    secret: {}
  phase: done
  repositories:
  - action: release
    address: https://github.com/linuxsuren-bot/test
    branch: master
    name: test
    provider: github
    version: v0.0.8
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.4
status:
  conditions:
  - conditionType: release
    message: https://github.com/linuxsuren-bot/test was released
    status: success
